### ISSUE TITLE
Support Swift_Image when adding attachments

### ISSUE THREAD

**Issue by leevigraham** [OpenBuildings/postmark#19]
Hi guys,

I'm comparing a Postmark Transport I wrote a  while ago with your implementation and it looks like you haven't considered Swift_Image attachments: https://github.com/OpenBuildings/postmark/blob/master/src/Swift_Transport_PostmarkTransport.php#L165

I haven't tested your implementation yet so I could be wrong but I thought I would throw it out there.

http://swiftmailer.org/docs/messages.html#embedding-inline-media-files

Cheers Leevi

**Comment by hkdobrev** [comment]
Embedded images are supported. Tests have been added in #41.

**Comment by leevigraham** [comment]
Forgot about this one 👍
