### ISSUE TITLE
Send only \Swift_TransportException

### ISSUE THREAD

**Issue by romaricdrigon** [OpenBuildings/postmark#27]
Hi,

In case of API errors, the mailer throws "regular" `\Exception`.
SwiftMailer includes a specific Exception class, `\Swift_TransportException`. Only those are catched by various plugins and decorators. Then using those - or extending those to something like `PostMarkApiException` would be nice!

**Comment by hkdobrev** [comment]
Hi @romaricdrigon,

Thanks for this! We could definitely make use of the `\Swift_TransportException`. However in the time being you could catch `Postmark\Exception` which extends `\Exception` for Postmark API errors. Its code is set to the API error code which Postmark uses. https://github.com/OpenBuildings/postmark/blob/a51bb76b79164ef251c4dba48678f37df3ad3d86/src/Exception.php

**Comment by romaricdrigon** [comment]
Definitely, for now I overrode SwiftMailer bundle listener to catch exceptions :)

**Comment by hkdobrev** [comment]
@romaricdrigon Would you be interested in opening a pull request with this change?

**Comment by romaricdrigon** [comment]
Sure, right away!

**Comment by romaricdrigon** [comment]
Closing issue in favor of PR #28
