### ISSUE TITLE
multipart/related not supported

### ISSUE THREAD

**Issue by darkbluesun** [OpenBuildings/postmark#42]
![image](https://cloud.githubusercontent.com/assets/2162344/25831951/d9a0beae-34aa-11e7-849b-2ee099918f2c.png)
My html message is set as plain text, because this type is not considered. help

**Comment by hkdobrev** [comment]
Fixed in #43. Released as [`0.3.6`](https://github.com/OpenBuildings/postmark/releases/tag/0.3.6).
